export const reduxConstants = {
    STORE_USER_DATA: 'STORE_USER_DATA',
    STORE_MOVIES: 'STORE_MOVIES',
    HANDLE_INPUT: 'HANDLE_INPUT',
    HANDLE_FILE: 'HANDLE_FILE',
    EDIT_MOVIE: 'EDIT_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    CANCEL_MOVIE_CREATION: 'CANCEL_MOVIE_CREATION'
}